[MainteSettings]
PrinterCount=

; -------------------------------------------------------------------
; Settings about each printer.
; UsbNo				:	USB ID?i0~7 with no duplication?j
; SizeId			:	Size ID(defined by ASKDllDef.h)
; Enable			:	0: unuse?@
;						others?Fuse
; PaperRemainCount	:	remain count of ribbons/papers
; -------------------------------------------------------------------
[1]
UsbNo=
SizeId=
Enable=
PaperRemainCount=
DeviceId=
Serial=

[2]
UsbNo=
SizeId=
Enable=
PaperRemainCount=
DeviceId=
Serial=

[3]
UsbNo=
SizeId=
Enable=
PaperRemainCount=
DeviceId=
Serial=

[4]
UsbNo=
SizeId=
Enable=
PaperRemainCount=
DeviceId=
Serial=

[5]
UsbNo=
SizeId=
Enable=
PaperRemainCount=
DeviceId=
Serial=

[6]
UsbNo=
SizeId=
Enable=
PaperRemainCount=
DeviceId=
Serial=

[7]
UsbNo=
SizeId=
Enable=
PaperRemainCount=
DeviceId=
Serial=

[8]
UsbNo=
SizeId=
Enable=
PaperRemainCount=
DeviceId=
Serial=

; -------------------------------------------------------------------
; Settings about printer.
; ModelOrder	:	defines the printer model id order
;					(corresponds with the index of model dependancy parameter)
; -------------------------------------------------------------------
[Printer]
ModelOrder=0,2,4,6,9,11,101,5000

; -------------------------------------------------------------------
; Settings about paper counter.
; UseSoftwareCounter	:	0(unuse software counter)
;							others(use software counter)
; -------------------------------------------------------------------
[PaperRemainSettings]
UseSoftwareCounter=0

; -------------------------------------------------------------------
; Settings about each print size.
; SizeSetting_N :N equals to size id
; UpdateSoftwareCountThreshold	: the threshold of updating software counter
; DefaultSoftwareCount			: default value of full paper remains by printer model id.
;								  "," is delimiter and index corresponds with "ModelOrder".
;	"ASK-1000(0),ASK-1500(2),ASK-4000(4),ASK-2000(6),ASK-4000A(9),ASK-2500(11),ASK-300(101),ASK-5000(5000)"
; -------------------------------------------------------------------
[SizeSetting_1]
UpdateSoftCountThreshold=50
DefaultSoftwareCount=,600,,600,,600,450,

[SizeSetting_2]
UpdateSoftCountThreshold=50
DefaultSoftwareCount=,600,,600,,600,400,

[SizeSetting_4]
UpdateSoftCountThreshold=50
DefaultSoftwareCount=,308,,308,,308,230,

[SizeSetting_8]
UpdateSoftCountThreshold=50
DefaultSoftwareCount=,273,,273,,273,200,

[SizeSetting_16]
UpdateSoftCountThreshold=50
DefaultSoftwareCount=,,,,170,,,

[SizeSetting_32]
UpdateSoftCountThreshold=50
DefaultSoftwareCount=,,200,,,,,200

[SizeSetting_96]
UpdateSoftCountThreshold=50
DefaultSoftwareCount=,,200,,,,,200

[SizeSetting_128]
UpdateSoftCountThreshold=50
DefaultSoftwareCount=,,,,,,200,
