[SizeNum]
Num=23

; -------------------------------------------------------------------
; 各出力サイズに関する設定
; Name				:	サイズ名
; SizeId			:	サイズ識別子(ASKDllDef.h で定義される)
; PrinterId			:	該当サイズを印刷可能なプリンター機種ID
; Width				:	幅のPixel値（ケラレ有り）
; Height			:	高さのPixel値（ケラレ有り）
; WidthMM			:	幅のmm値（小数点1位を扱うため、*10した値）
; HeightMM			:	高さのmm値（小数点1位を扱うため、*10した値）
; CutPattern		:	カットタイプ
; OutputMagSize		:	プリンター情報ファイルに出力するサイズかどうか
; WidthMM/HeightMM の組み合わせに一致するSizeIdは必ず一つであること
; (例：ASK-300用のL(127x89)もSizeIdは1)
; -------------------------------------------------------------------
[1]
Name=89x127
SizeId=1
PrinterId=2,6,11
Width=1536
Height=1074
WidthMM=1270
HeightMM=890
CutPattern=1
OutputMagSize=1

[2]
Name=102x152
SizeId=2
PrinterId=2,6,11
Width=1832
Height=1228
WidthMM=1520
HeightMM=1020
CutPattern=1
OutputMagSize=1

[3]
Name=178x127
SizeId=4
PrinterId=2,6,11
Width=1536
Height=2130
WidthMM=1270
HeightMM=1780
CutPattern=1
OutputMagSize=1

[4]
Name=203x152
SizeId=8
PrinterId=2,6,11
Width=1832
Height=2432
WidthMM=1520
HeightMM=2030
CutPattern=1
OutputMagSize=0

[5]
Name=229x152
SizeId=8
PrinterId=2,6,11
Width=1832
Height=2748
WidthMM=1520
HeightMM=2290
CutPattern=1
OutputMagSize=1

[6]
Name=102x152_Multi
SizeId=8
PrinterId=2,6,11
Width=1832
Height=2748
WidthMM=1520
HeightMM=1020
CutPattern=2
OutputMagSize=0

[7]
Name=254x203
SizeId=32
PrinterId=4
Width=2444
Height=3044
WidthMM=2030
HeightMM=2540
CutPattern=1
OutputMagSize=1

[8]
Name=305x203
SizeId=64
PrinterId=4
Width=2444
Height=3644
WidthMM=2030
HeightMM=3050
CutPattern=1
OutputMagSize=1

[9]
Name=102x203
SizeId=64
PrinterId=4
Width=2444
Height=1244
WidthMM=2030
HeightMM=1020
CutPattern=3
OutputMagSize=0

[10]
Name=297x210
SizeId=16
PrinterId=9
Width=2528
Height=3556
WidthMM=2100
HeightMM=2970
CutPattern=1
OutputMagSize=1

[11]
Name=148x210
SizeId=16
PrinterId=9
Width=2528
Height=1800
WidthMM=2100
HeightMM=1480
CutPattern=2
OutputMagSize=0

; 以下、ASK-300用のサイズ定義（Pixel値が異なる）
[12]
Name=89x127
SizeId=1
PrinterId=101
Width=1568
Height=1076
WidthMM=1270
HeightMM=890
CutPattern=1
OutputMagSize=1

[13]
Name=102x152
SizeId=2
PrinterId=101
Width=1864
Height=1228
WidthMM=1520
HeightMM=1020
CutPattern=1
OutputMagSize=1

[14]
Name=178x127
SizeId=4
PrinterId=101
Width=1568
Height=2128
WidthMM=1270
HeightMM=1780
CutPattern=1
OutputMagSize=1

[15]
Name=203x152
SizeId=128
PrinterId=101
Width=1864
Height=2422
WidthMM=1520
HeightMM=2030
CutPattern=1
OutputMagSize=1

[16]
Name=229x152
SizeId=8
PrinterId=101
Width=1864
Height=2730
WidthMM=1520
HeightMM=2290
CutPattern=1
OutputMagSize=1

[17]
Name=102x152_Multi
SizeId=136
PrinterId=101
Width=1864
Height=1228
WidthMM=1520
HeightMM=1020
CutPattern=2
OutputMagSize=0

; 以下、ASK-5000用のサイズ定義（Pixel値が異なる）
[18]
Name=254x203
SizeId=32
PrinterId=5000
Width=2446
Height=3036
WidthMM=2030
HeightMM=2540
CutPattern=1
OutputMagSize=1

[19]
Name=305x203
SizeId=64
PrinterId=5000
Width=2446
Height=3636
WidthMM=2030
HeightMM=3050
CutPattern=1
OutputMagSize=1

[20]
Name=102x203
SizeId=64
PrinterId=5000
Width=2446
Height=1229
WidthMM=2030
HeightMM=1020
CutPattern=3
OutputMagSize=0

[21]
Name=152x203
SizeId=64
PrinterId=5000
Width=2446
Height=1831
WidthMM=2030
HeightMM=1520
CutPattern=3
OutputMagSize=0

;=====ましかく=====
[22]
Name=89x89
SizeId=256
PrinterId=101
Width=1568
Height=1076
WidthSquare=1118
HeightSquare=1076
WidthMM=890
HeightMM=890
CutPattern=1
OutputMagSize=1

[23]
Name=102x102
SizeId=512
PrinterId=101
Width=1864
Height=1228
WidthSquare=1264
HeightSquare=1228
WidthMM=1020
HeightMM=1020
CutPattern=1
OutputMagSize=1
