;
;PrinterFunctionSetting configuration file
;

[Header]
Cnt=2

Text1="Serial Number"
Width1=270

Text2="Paper Type"
Width2=265

[Caption]
OK="OK"
Cancel="Cancel"
TitleMain="ASK Printer Setting Tool"
TitleError="Error"
NoPrinterMsg="Printer not exist."
InputErrMsg="File input failed."
OutputErrMsg="File output failed."

;Surface value, If the setting for each printer is required
[Surface]
1=Glossy, Matte
11=Sticker
20=Square

[Default]
Surface=1
