[PrintMode]
;面種,画質=MCP_PRINT_MODE
;	面種
;		グロッシー	=	1
;		マット		=	2
;		シール		=	11
;		ましかく	=	20
;	画質
;		標準画質	=	0
;		高画質		=	1
;	MCP_PRINT_MODE定義
;		MCP_PRINT_MODE_SPEED				(0)	/* Print speed priority mode		*/
;		MCP_PRINT_MODE_QUALITY				(1)	/* Print quality priority mode		*/
;		MCP_PRINT_MODE_QUALITY_MATTE2       (5) /* PPrintMode_5 (Only ASK-300)      */
1,0=0
1,1=1
2,0=5
2,1=5
11,0=0
11,1=1
20,0=5
20,1=5
