;
;SortPrintSetting configuration file
;

[DlgType]
MiniSize=1

[Caption]
OK="OK"
Cancel="Cancel"

TitleMain="Sort Print Setting"
TitleConfirm="Confirm"
Msg1="Change does not reflect, \r\nDo you want to quit?"
Msg2="The value of the feeding length(Length Adjust) is out of valid range.\r\nPlease set the value from 89.0mm to 1000.0mm."
Msg3="The value of the OrderNumber Font Size is out of valid range.\r\nPlease set the value from 6point to 200point."
Msg4="The value of the OrderNumber Position is out of valid range.\r\nPlease set the value from 0% to 100%."
Msg5="The value of the Image Layer Position is out of valid range.\r\nPlease set the value from 0% to 100%."
Msg6="The value of the Image Layer Size is out of valid range.\r\nPlease set the value from 0% to 100%."
Msg7="The value of the OrderInfo Font Size is out of valid range.\r\nPlease set the value from 6point to 200point."
Msg8="The value of the OrderInfo Position is out of valid range.\r\nPlease set the value from 0% to 100%."

PrinterGr=Printer
SortPrintGr=Sort Print Setting
SortPrint=Sort Print:
SortPrintOn=On
SortPrintOff=Off
PrintPosGr=Print Order
PrintPosFirst=First
PrintPosLast=Last
PrintTypeGr=Print Contents
PrintTypePict=Order Number+Picture
PrintTypeNumber=Order Number Only
PrintTypeImageFile=Image File:
PrintTypeImageFileRef=ref...
PrintLengthGr=Length Adjust
PrintLengthNon=None
PrintLengthSpec=Fixed
PrintLengthUnit=(mm)
OrderNumPictSettingGr=OrderNumber/Picture Setting
PicturePosition=Image Layer Position:
PictureSize=Image Layer Size:
OrderNumPosition=OrderNumber Position:
OrderNumFontSize=OrderNumber Font Size:
OrderNumFontSizeUnit=(pt)
Percent=(%)
SelectColor=Font Color
SampleFont=ABC
OrderInfoPosition=OrderInfo Position:
OrderInfoFontSize=OrderInfo Font Size:
