[Printer]
Cnt=0

[Printer-All]
FontName=Microsoft Sans Serif
LineSpaceSize=40

;for example
;[Printer-X]
;PrinterID=A
;SortPrintOn=0
;PrintOrder=0
;PrintContents=0
;PrintImagePath=
;PicturePositionX=15
;PicturePositionY=20
;PictureSizeX=70
;PictureSizeY=56
;OrderPositionX=15
;OrderPositionY=12
;OrderNumberFontSize=60
;OrderNumberFontColor=000000
;OrderInfoPositionX=15
;OrderInfoPositionY=20
;OrderInfoFontSize=60
;OrderInfoFontColor=000000
